[general]
inputtimeshift = 2      # this time in hours will be added to the "in" time of the message that gets sent to the client
statustimeshift = 2     # this time in hours will be added to the "status" time of the message (startsAt/endsAt) that gets sent to the client

[http]
host = "0.0.0.0"
port = 9119
clearsecret = "your_secret_key"

[meshtastic.connection]
tty = "/dev/ttyACM0"
# Single node (backward compatible):
nodeid = 123456789
# OR multiple nodes (new format):
# nodeids = [123456789, 987654321, 555666777]
maxsendingattempts = 30
timeout = 60

