name: python-package

on:
  # push:
  #   branches: [main]
  #   paths:
  #     - "**"
  #     - "!README.md"
  #     - "!.github/workflows/update-dockerhub.yml"
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "**"
  #     - "!README.md"
  #     - "!.github/workflows/update-dockerhub.yml"

  repository_dispatch:
    types: [release-created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/alertmanagermeshtastic
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: replace version
        run: sed -i 's|0.01-dev1|${{ github.event.client_payload.next_release_tag }}|g' src/alertmanagermeshtastic/__init__.py
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
